In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6])

In [6]:
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
print(arr)

[1 2 3 4 5 6]


In [9]:
l = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [10]:
print(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
zero = np.zeros([2,4])

In [18]:
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
 linSPC = np.linspace(1,10,30) # creates 30 equally spaced numbers b/w 1 to 10

In [21]:
print(linSPC)

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]


In [22]:
np.random.rand(10) #generates random numbers NORMALISED VALUES always between 0-1

array([0.70999386, 0.39901232, 0.28429133, 0.5164866 , 0.42100375,
       0.5765309 , 0.32267998, 0.15577562, 0.15649669, 0.28490515])

In [23]:
np.random.randn(10) # generates random number STANDARIZED VALUES always between -3 to 3

array([-0.31714324,  0.06849919,  0.55916817,  1.9425918 ,  1.33709148,
       -1.46817548, -1.33374557,  0.49805908, -0.63428428, -0.31205054])

In [24]:
np.random.randint(10) #generates a random number from 0 to 10

7

In [25]:
np.random.randint(10,30,6) #generate 6 random numbers b/w 10 to 30

array([20, 20, 10, 16, 23, 12], dtype=int32)

In [26]:
np.random.randint(10,30)

13

In [27]:
l.shape #rows and coloumns, dont use bracket, its an attribute not methord

(3, 3)

In [28]:
l.size #no of elements

9

In [29]:
l.dtype #data type of array 

dtype('int64')

In [30]:
l.min

<function ndarray.min>

In [31]:
l.min()

np.int64(1)

In [33]:
print(l.min()) #min element, same is l.max()

1


In [34]:
print(l.sum()) #sum of all digits

45


In [36]:
#axis 1 is rowwise ->
#axis 0 is coloumnwise , downwards

In [38]:
print(np.sum(l)) #works with or without axis

45


In [39]:
print(np.sum(l, axis=1))

[ 6 15 24]


In [41]:
l.mean()

np.float64(5.0)

In [42]:
print(l.mean())

5.0


In [43]:
print(l.std())

2.581988897471611


In [44]:
print(l.argmax()) # index of max element and similarly argmin

8


In [45]:
n1= np.arange(1,31)

In [46]:
print(n1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [48]:
n1.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [49]:
print(n1) #original n1 hasnt changed  

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [50]:
n2 = n1.reshape(5,6)

In [51]:
print(n2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
