In [5]:
import numpy as np

In [7]:
l = np.arange(1,11)
print(l)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
l[3:8] #from index 3 to 7 

array([4, 5, 6, 7, 8])

In [9]:
l[::2] #start to end step 2 elements

array([1, 3, 5, 7, 9])

In [10]:
# l[start : stop : step]

In [12]:
l[4]

np.int64(5)

In [13]:
print(l[4])

5


In [17]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [18]:
arr[0] #row indexing 

array([1, 2, 3, 4, 5])

In [25]:
arr[0,0]

np.int64(1)

In [26]:
print(arr[2,4]) #[row,col]

15


In [29]:
arr[0:2, 1:4]  #row 0 to 1 &  col 1 to 3

array([[2, 3, 4],
       [7, 8, 9]])

In [31]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [32]:
print(arr[:,2]) #slicing Columns

[ 3  8 13 18 23 28]


In [39]:
evens = np.array
for i in l:
    if i%2 == 0: 
        print(i)

2
4
6
8
10


In [40]:
print(evens)

<built-in function array>


In [41]:
arr=arr[arr%2==0]   #boolean indexing, keep only the true values

In [42]:
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [43]:
l=l[l%2==0]
print(l)

[ 2  4  6  8 10]
