In [35]:
import numpy as np

In [36]:
#ARITHIMATIC OPERATIONS

In [37]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([6,7,8,9,10,11])

In [38]:
#Addition 
a1 + a2 
#similarly other operations

array([ 7,  9, 11, 13, 15, 17])

In [39]:
#BROADCASTING

In [40]:
# add +10 to every element
a1 + 10

array([11, 12, 13, 14, 15, 16])

In [41]:
#Deep and Shallow COPY

In [42]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
#When we slice an Numpy Array and save it into a variable, then if we make changes to that sliced variable,
#it does not chnage anything in the Original Array

In [44]:
#Hence in Numpy Array, Deep Copies are made, while in lists, Shallow Copies are made

In [45]:
b = a
b[0]= 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
# if we do b = a then they both point to the same part in the memory, hence a shallow copy 

In [48]:
c = a.copy()

In [49]:
c[0] = 1
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
# if we use .copy() function, it makes a deep copy

In [59]:
A = np.arange(1,11).reshape(2,5)
B = np.arange(10,20).reshape(5,2)

In [61]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
B

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [63]:
A @ B # Matrix Multiplication

array([[230, 245],
       [580, 620]])

In [65]:
A.T   # Transpose

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [66]:
# ADVANCED ARRAY MANIPULATION

In [67]:
# We can only stack arrays and not MATRICES

In [68]:
np.vstack((a,b))   #vstack mean Vertical Stacking, Similarly hstack 

array([[99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20],
       [99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [69]:
np.hstack((a,b))

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20])

In [70]:
np.column_stack((a,b))

array([[99, 99],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6,  6],
       [ 7,  7],
       [ 8,  8],
       [ 9,  9],
       [10, 10],
       [11, 11],
       [12, 12],
       [13, 13],
       [14, 14],
       [15, 15],
       [16, 16],
       [17, 17],
       [18, 18],
       [19, 19],
       [20, 20]])

In [72]:
np.hsplit(a,2) #horizontally split 'a' into 2 parts

[array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])]