In [172]:
import numpy as np

In [173]:
data = np.array([[18,72,78],[19,99,89],[17,88,71],[18,72,78],[12,78,71],[15,98,99]]) #Age, Maths marks, Sci Marks
data
print(data)

[[18 72 78]
 [19 99 89]
 [17 88 71]
 [18 72 78]
 [12 78 71]
 [15 98 99]]


In [174]:
#get the shape of marks
data.shape

(6, 3)

In [175]:
#avg age
sum = np.sum(data, axis=0)
avg=sum[0]/6
print(avg)

16.5


In [176]:
# OR 
np.mean(data[:,0])

np.float64(16.5)

In [177]:
#Print all Maths Marks
print(data[:,1])

[72 99 88 72 78 98]


In [178]:
#max Science marks
print(data[:,2].max())

99


In [179]:
#Info of Student having marks greater than 90 in maths
print(data[data[:,1]>=90])

[[19 99 89]
 [15 98 99]]


In [180]:
#Increase maths marks by 5
data[:,1] = data[:,1] +5
print(data)

[[ 18  73  78]
 [ 19 100  89]
 [ 17  89  71]
 [ 18  73  78]
 [ 12  79  71]
 [ 15  99  99]]


In [181]:
#how many students are younger than 19
print(data[data[:,0]<19])

[[18 73 78]
 [17 89 71]
 [18 73 78]
 [12 79 71]
 [15 99 99]]


In [182]:
#Avg Marks of Both Subjects
print("AVG Maths Marks : ", data[:,1].mean() ,"AVG Science Marks : ", data[:,2].mean())

AVG Maths Marks :  85.5 AVG Science Marks :  81.0


In [183]:
#Get Data of Students who scored atleast 80 in both subjects
print(data[(data[:,1]>=80) & (data[:,2]>=80)])

[[ 19 100  89]
 [ 15  99  99]]


In [184]:
#Replace all marks of science <75 to 0
data[:,2][data[:,2]<75]=0
data

array([[ 18,  73,  78],
       [ 19, 100,  89],
       [ 17,  89,   0],
       [ 18,  73,  78],
       [ 12,  79,   0],
       [ 15,  99,  99]])